CREATE TABLE [Payments2].[Commitment]
(
	[CommitmentId] [bigint] NOT NULL,
	[SequenceId] [varchar](25) NOT NULL,
	[Uln] [bigint] NOT NULL,
	[Ukprn] [bigint] NOT NULL,
	[AccountId] [bigint] NOT NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[AgreedCost] [decimal](15, 2) NOT NULL,
	[StandardCode] [bigint] NULL,
	[ProgrammeType] [int] NULL,
	[FrameworkCode] [int] NULL,
	[PathwayCode] [int] NULL,
	[PaymentStatus] [int] NOT NULL,
	[PaymentStatusDescription] [varchar](50) NOT NULL,
	[Priority] [int] NOT NULL,
	[EffectiveFromDate] [date] NOT NULL,
	[EffectiveToDate] [date] NULL,
	[LegalEntityName] [nvarchar](100) NULL,
	[TransferSendingEmployerAccountId] [bigint] NULL,
	[TransferApprovalDate] [datetime] NULL,
	[PausedOnDate] [datetime2](7) NULL,
	[WithdrawnOnDate] [datetime2](7) NULL,
	[AccountLegalEntityPublicHashedId] [char](6) NULL, 
    [AccountSequenceId] BIGINT NOT NULL, 
    [VersionId] BIGINT NOT NULL, 
    CONSTRAINT [PK_Commitment] PRIMARY KEY ([CommitmentId], [SequenceId]),
)
