CREATE TABLE [Payments2].[JobEvent]
(
	JobEventId BIGINT NOT NULL IDENTITY(1,1) CONSTRAINT PK_JobEvent PRIMARY KEY CLUSTERED,
	JobId BIGINT NOT NULL CONSTRAINT FK_JobEvent__Job FOREIGN KEY REFERENCES [Payments2].[Job] (JobId),
	EventId UNIQUEIDENTIFIER NOT NULL,
	ParentEventId UNIQUEIDENTIFIER NULL,
	[Status] TINYINT NOT NULL CONSTRAINT FK_JobEvent__JobEventStatus FOREIGN KEY REFERENCES [Payments2].[JobEventStatus] (Id) CONSTRAINT DF_Job_Event__Status DEFAULT (1),
	StartTime DATETIME2 NOT NULL CONSTRAINT DF_JobEvent__StartTime DEFAULT (SYSDATETIME()),
	EndTime DATETIME2 NULL
)