Create TABLE [Payments2].[Job]( 
	JobId BIGINT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Job PRIMARY KEY CLUSTERED,
	JobType TINYINT NOT NULL CONSTRAINT FK_Job__JobType FOREIGN KEY REFERENCES [Payments2].[JobType] (Id),
	StartTime DATETIMEOFFSET NOT NULL CONSTRAINT DF_Job__StartTime DEFAULT (SYSDATETIME()),	
	EndTime DATETIMEOFFSET NULL, 
	[Status] TINYINT NOT NULL CONSTRAINT FK_Job__JobStatus FOREIGN KEY REFERENCES [Payments2].[JobStatus] (Id) CONSTRAINT DF_Job__Status DEFAULT (1),
	CreationDate DATETIME NOT NULL CONSTRAINT DF_Job__CreationDate DEFAULT (GETDATE()),
	DCJobId BIGINT NULL,
	Ukprn BIGINT NULL, 
	IlrSubmissionTime DATETIME NULL,
	CollectionYear SMALLINT NOT NULL,
	CollectionPeriod TINYINT NOT NULL,
	INDEX IX_Job__DCJobId_Ukprn NONCLUSTERED (DCJobId, Ukprn)
)