Create TABLE [Payments2].[Job]( 
	JobId BIGINT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Job PRIMARY KEY CLUSTERED,
	StartTime DATETIME2 NOT NULL CONSTRAINT DF_Job__StartTime DEFAULT (SYSDATETIME()),
	EndTime DATETIME2 NULL, 
	[Status] TINYINT NOT NULL CONSTRAINT FK_Job__JobStatus FOREIGN KEY REFERENCES [Payments2].[JobStatus] (Id) CONSTRAINT DF_Job__Status DEFAULT (1)
)