parameters:
  azureSubscription:
  resourceGroupName:
  location: 'West Europe'
  dataFactoryName:
  keyVaultName:
  sharedSqlPrivateEndpoint:
  sharedSqlPrivateEndpointFqdns:
  DatamartStaginglinkedservices:
  DatamartStaginglinkedDB:
  DatamartSqlPrivateEndpoint:


steps:
- task: AzurePowerShell@4
  displayName: Disable Triggers
  inputs:
    azureSubscription: '${{ parameters.azureSubscription }}'
    ScriptPath: '$(Pipeline.Workspace)/drop/Infrastructure/SFA.DAS.Payments.ADF/scripts/Set-AzDataFactoryTriggerState.ps1'
    ScriptArguments: '-DataFactoryName "${{ parameters.dataFactoryName }}" -ResourceGroupName "${{ parameters.resourceGroupName }}" -TriggerState disable'
    azurePowerShellVersion: LatestVersion

- task: AzureResourceGroupDeployment@2
  displayName: Deploy Data Factory
  inputs:
    azureSubscription: '${{ parameters.azureSubscription }}'
    resourceGroupName: '${{ parameters.resourceGroupName }}'
    location: ${{ parameters.location }}
    csmFile: '$(Pipeline.Workspace)/drop/Infrastructure/SFA.DAS.Payments.ADF/DCOL-DAS-DataFactoryDAS-WEU/arm_template.json'
    overrideParameters: '-factoryName "${{ parameters.dataFactoryName }}" -AzureKeyVault1_properties_typeProperties_baseUrl "https://${{ parameters.keyVaultName }}.vault.azure.net/" -shared_sql_private_endpoint_properties_privateLinkResourceId "${{ parameters.sharedSqlPrivateEndpoint }}" -shared_sql_private_endpoint_properties_fqdns ["${{ parameters.sharedSqlPrivateEndpointFqdns }}"] -datamart_stagingDB_linkedservices_properties_typeProperties_server ["${{ parameters.DatamartStaginglinkedservices }}"] -datamart_stagingDB_linkedservices_properties_typeProperties_database ["${{ parameters.DatamartStaginglinkedDB }}"] -datamart_sql_private_endpoint_properties_privateLinkResourceId ["${{ parameters.DatamartSqlPrivateEndpoint }}"] -datamart_sql_private_endpoint_properties_fqdns ["${{ parameters.DatamartStaginglinkedservices }}"]'

- task: AzurePowerShell@4
  displayName: Enable Triggers
  inputs:
    azureSubscription: '${{ parameters.azureSubscription }}'
    ScriptPath: '$(Pipeline.Workspace)/drop/Infrastructure/SFA.DAS.Payments.ADF/scripts/Set-AzDataFactoryTriggerState.ps1'
    ScriptArguments: '-DataFactoryName "${{ parameters.dataFactoryName }}" -ResourceGroupName "${{ parameters.resourceGroupName }}" -TriggerState enable'
    azurePowerShellVersion: LatestVersion