variables:
- group: Common - Project Level
- group: Common - Connection String
- group: Common - Database Names
- group: Common - Database Usernames

resources:
  repositories:
  - repository: self

trigger:
  branches:
    include:
    - master
    - PV2-3091
  batch: true
  paths:
    include:
    - Infrastructure/SFA.DAS.Payments.SFCluster.Alerts
    exclude:
    - Infrastructure/SFA.DAS.Payments.ADF
    - Infrastructure/SFA.DAS.Payments.Monitoring.Metrics

stages:
- stage: Publish_SFClusterAlerts
  displayName: Publish SFClusterAlerts

  jobs:
  - template: pipeline/publish.yml

#- stage: Deploy_DAS
#  dependsOn: Publish_SFClusterAlerts
#  displayName: Deploy to DAS
#  variables:
#  - name: tagEnvironment
#    value: Dev/Test
#  - group: DCOL-DAS - Environment Key Vault Secrets
#  jobs:
#  - template: pipeline/deploy.yml
#    parameters:
#      pool: DCT Build Pool
#      environmentName: DAS
#      azureSubscription: DCT-VSO
#      metricAlerts_VM_CPU_Alert_name: VM-DAS-CPU-Alert
#      virtualMachineScaleSets_monitor_externalid: /subscriptions/4ff47917-ac4e-432a-b314-a6525434afcb/resourceGroups/DCOL-SDW-ServiceFabricDas-WEU/providers/Microsoft.Compute/virtualMachineScaleSets/monitor
#      actionGroups_dcol_sdw_dasalerts_actiongroup_externalid: /subscriptions/4FF47917-AC4E-432A-B314-A6525434AFCB/resourceGroups/dcol-sdw-ops-weu/providers/microsoft.insights/actionGroups/dcol-sdw-dasalerts-actiongroup
#      metricAlerts_VM_Available_Memory_Alert_name: VM-DAS-Available-Memory-Alert
#      actiongroups_dcol_sdw_dasalerts_actiongroup_weu_externalid: /subscriptions/4ff47917-ac4e-432a-b314-a6525434afcb/resourceGroups/dcol-sdw-servicefabricdas-weu/providers/microsoft.insights/actiongroups/dcol-sdw-dasalerts-actiongroup-weu
#      metricAlerts_VM_Availability_Alert_name: VM-Availability-Alert
#      actionGroups_SFCluster_VMAlerts_externalid: /subscriptions/4FF47917-AC4E-432A-B314-A6525434AFCB/resourceGroups/DCOL-SDW-ServiceFabricDas-WEU/providers/microsoft.insights/actionGroups/SFCluster-VMAlerts


#- stage: Deploy_DST
#  dependsOn: Publish_MonitoringMetrics
#  displayName: Deploy to DST
#  variables:
#  - name: tagEnvironment
#    value: Dev/Test
#  - group: DCOL-DST - Environment Key Vault Secrets
#  jobs:
#  - template: pipeline/deploy.yml
#    parameters:
#      pool: DCT Build Pool
#      environmentName: DST
#      azureSubscription: DCT-VSO
#      storageAccountName: dcoldststoragemonitorweu
#      workspaceResourceId: /subscriptions/12f72527-6622-45d3-90a4-0a5d3644c45c/resourcegroups/dcol-dev-oms-weu/providers/microsoft.operationalinsights/workspaces/dcol-dev-oms-weu
#      dasActionGroupWebhookUri1: $(dasActionGroupWebhookUri)
#      mgDasActionGroupWebhookUri1: $(mgDasActionGroupWebhookUri)
#      smartDetectionActionGroupId: /subscriptions/12F72527-6622-45D3-90A4-0A5D3644C45C/resourceGroups/DCOL-DST-AppSrvEnv-WEU/providers/microsoft.insights/actionGroups/application%20insights%20smart%20detection
#      serviceBusActionGroupId: /subscriptions/12F72527-6622-45D3-90A4-0A5D3644C45C/resourceGroups/DCOL-DST-AppSrvEnv-WEU/providers/microsoft.insights/actionGroups/application%20insights%20smart%20detection
#      dasAlertSlackChannelUri: NoValue
#      mngAlertSlackChannelUri: NoValue
#      appInsightsApiKey: $(AppInsightsAuthValue)
       
      

#- stage: Deploy_SIT
#  dependsOn: 
#  - Publish_MonitoringMetrics
#  - Deploy_DST
#  displayName: Deploy to SIT
#  variables:
#  - name: tagEnvironment
#    value: Dev/Test
#  - group: DCOL-SIT - Environment Key Vault Secrets
#  jobs:
#  - template: pipeline/deploy.yml
#    parameters:
#      pool: DCT Build Pool
#      environmentName: SIT
#      azureSubscription: DCT-VSO
#      storageAccountName: dcolsitstoragemonitorweu
#      workspaceResourceId: /subscriptions/12f72527-6622-45d3-90a4-0a5d3644c45c/resourcegroups/dcol-dev-oms-weu/providers/microsoft.operationalinsights/workspaces/dcol-dev-oms-weu
#      dasActionGroupWebhookUri1: $(dasActionGroupWebhookUri)
#      mgDasActionGroupWebhookUri1: $(mgDasActionGroupWebhookUri)
#      smartDetectionActionGroupId: /subscriptions/12F72527-6622-45D3-90A4-0A5D3644C45C/resourceGroups/DCOL-SIT-AppSrvEnv-WEU/providers/microsoft.insights/actionGroups/application%20insights%20smart%20detection
#      serviceBusActionGroupId: /subscriptions/12F72527-6622-45D3-90A4-0A5D3644C45C/resourceGroups/DCOL-OPS-OPS-WEU/providers/microsoft.insights/actionGroups/application%20insights%20smart%20detection
#      dasAlertSlackChannelUri: NoValue
#      mngAlertSlackChannelUri: NoValue
#      appInsightsApiKey: $(AppInsightsAuthValue)
      

- stage: Deploy_SDW
  dependsOn: 
  - Publish_SFClusterAlerts
# - Deploy_SIT
  displayName: Deploy to SDW
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-SDW - Environment Key Vault Secrets
  jobs:
  - template: pipeline/deploy.yml
    parameters:
      pool: DCT Build Pool
      environmentName: SDW
      azureSubscription: DCOL-Shadow
      metricAlerts_VM_CPU_Alert_name: VM-SDW-CPU-Alert
      virtualMachineScaleSets_monitor_externalid: /subscriptions/4ff47917-ac4e-432a-b314-a6525434afcb/resourceGroups/DCOL-SDW-ServiceFabricDas-WEU/providers/Microsoft.Compute/virtualMachineScaleSets/monitor
      actionGroups_dcol_dasalerts_actiongroup_externalid: /subscriptions/4FF47917-AC4E-432A-B314-A6525434AFCB/resourceGroups/dcol-sdw-ops-weu/providers/microsoft.insights/actionGroups/dcol-sdw-dasalerts-actiongroup
      metricAlerts_VM_Available_Memory_Alert_name: VM-SDW-Available-Memory-Alert
      actiongroups_dcol_dasalerts_actiongroup_weu_externalid: /subscriptions/4ff47917-ac4e-432a-b314-a6525434afcb/resourceGroups/dcol-sdw-servicefabricdas-weu/providers/microsoft.insights/actiongroups/dcol-sdw-dasalerts-actiongroup-weu
      metricAlerts_VM_Availability_Alert_name: VM-SDW-Availability-Alert
      actionGroups_SFCluster_VMAlerts_externalid: /subscriptions/4FF47917-AC4E-432A-B314-A6525434AFCB/resourceGroups/DCOL-SDW-ServiceFabricDas-WEU/providers/microsoft.insights/actionGroups/SFCluster-VMAlerts
      

 
- stage: Deploy_MO
  dependsOn: 
  - Publish_SFClusterAlerts
  - Deploy_SDW
  displayName: Deploy to MO
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-MO - Environment Key Vault Secrets
  - group: Common - tags MO
  jobs:
  - template: pipeline/deploy.yml
    parameters:
      pool: DCT Build Pool
      environmentName: MO
      azureSubscription: DCOL-MO-VSTS
      metricAlerts_VM_CPU_Alert_name: VM-CPU-Alert-MO
      virtualMachineScaleSets_monitor_externalid: /subscriptions/2f538936-0715-4dfd-83da-6b8c5a399d6a/resourceGroups/dcol-mo-servicefabricdas-weu/providers/Microsoft.Compute/virtualMachineScaleSets/monitor
      actionGroups_dcol_dasalerts_actiongroup_externalid: /subscriptions/2f538936-0715-4dfd-83da-6b8c5a399d6a/resourceGroups/DCOL-MO-OPS-WEU/providers/microsoft.insights/actionGroups/SFA-FCS-MO-PV2
      metricAlerts_VM_Available_Memory_Alert_name: VM-Available-Memory-Alert-MO
      actiongroups_dcol_dasalerts_actiongroup_weu_externalid: /subscriptions/2f538936-0715-4dfd-83da-6b8c5a399d6a/resourceGroups/DCOL-MO-OPS-WEU/providers/microsoft.insights/actionGroups/SFA-FCS-MO-PV2
      metricAlerts_VM_Availability_Alert_name: VM-Availability-Alert-MO
      actionGroups_SFCluster_VMAlerts_externalid: /subscriptions/2f538936-0715-4dfd-83da-6b8c5a399d6a/resourceGroups/DCOL-MO-OPS-WEU/providers/microsoft.insights/actionGroups/SFA-FCS-MO-PV2

#- stage: Deploy_PP
#  dependsOn: 
#  - Publish_MonitoringMetrics
#  - Deploy_MO
#  displayName: Deploy to PP
#  variables:
#  - name: tagEnvironment
#    value: Pre-Production
#  - group: DCOL-PP - Environment Key Vault Secrets
#  jobs:
#  - template: pipeline/deploy.yml
#    parameters:
#      pool: DCT Build Pool
#      environmentName: PP
#      azureSubscription: DCOLPPVSTS
#      storageAccountName: dcolppstoragemonitorweu
#      workspaceResourceId: /subscriptions/931bc9f6-359c-4f65-a753-1ee191a1fd6c/resourcegroups/dcol-pp-ops-weu/providers/microsoft.operationalinsights/workspaces/dcol-pp-oms-weu
#      dasActionGroupWebhookUri1: $(dasActionGroupWebhookUri)
#      mgDasActionGroupWebhookUri1: $(mgDasActionGroupWebhookUri)
#      smartDetectionActionGroupId: /subscriptions/931BC9F6-359C-4F65-A753-1EE191A1FD6C/resourceGroups/DCOL-PP-AppSrvEnv-WEU/providers/microsoft.insights/actionGroups/application%20insights%20smart%20detection
#      serviceBusActionGroupId: /subscriptions/931BC9F6-359C-4F65-A753-1EE191A1FD6C/resourceGroups/DCOL-PP-ServiceFabricDAS-WEU/providers/microsoft.insights/actionGroups/DCOL-PP-dasalerts-actiongroup-WEU
#      dasAlertSlackChannelUri: $(SlackChannelUri)
#      mngAlertSlackChannelUri: $(SlackChannelUri2)
#      appInsightsApiKey: $(AppInsightsAuthValue)

- stage: Deploy_PD
  dependsOn: 
  - Publish_MonitoringMetrics
  - Deploy_MO
  displayName: Deploy to PD
  variables:
  - name: tagEnvironment
    value: Production
  - group: DCOL-PD - Environment Key Vault Secrets
  jobs:
  - template: pipeline/deploy.yml
    parameters:
      pool: DCT Build Pool
      environmentName: PD
      azureSubscription: DCOLPDVSTS
      metricAlerts_VM_CPU_Alert_name: VM-CPU-Alert-PD
      virtualMachineScaleSets_monitor_externalid: /subscriptions/6C93F7DC-6C36-4EA6-8DE3-3F4574F88027/DCOL-PD-ServiceFabricDas-WEU/providers/Microsoft.Compute/virtualMachineScaleSets/monitor
      actionGroups_dcol_dasalerts_actiongroup_externalid: /subscriptions/6C93F7DC-6C36-4EA6-8DE3-3F4574F88027/resourceGroups/DCOL-PD-ServiceFabricDAS-WEU/providers/microsoft.insights/actionGroups/DCOL-PD-dasalerts-actiongroup-WEU
      metricAlerts_VM_Available_Memory_Alert_name: VM-Available-Memory-Alert-PD
      actiongroups_dcol_dasalerts_actiongroup_weu_externalid: /subscriptions/6C93F7DC-6C36-4EA6-8DE3-3F4574F88027/resourceGroups/DCOL-PD-ServiceFabricDAS-WEU/providers/microsoft.insights/actionGroups/DCOL-PD-dasalerts-actiongroup-WEU
      metricAlerts_VM_Availability_Alert_name: VM-Availability-Alert-PD
      actionGroups_SFCluster_VMAlerts_externalid: /subscriptions/6C93F7DC-6C36-4EA6-8DE3-3F4574F88027/resourceGroups/DCOL-PD-ServiceFabricDAS-WEU/providers/microsoft.insights/actionGroups/DCOL-PD-dasalerts-actiongroup-WEU
