variables:
- group: Common - Project Level
- group: Common - Connection String
- group: Common - Database Names
- group: Common - Database Usernames

resources:
  repositories:
  - repository: self

trigger:
  branches:
    include:
    - master

  batch: true
  paths:
    include:
    - Infrastructure/SFA.DAS.Payments.DCR
    exclude:
    - Infrastructure/SFA.DAS.Payments.ADF
    - Infrastructure/SFA.DAS.Payments.Monitoring.Metrics
    - Infrastructure/SFA.DAS.Payments.SFCluster.Alerts

stages:
- stage: Publish_DCR_Rules
  displayName: Publish DCR_Rules

  jobs:
  - template: pipeline/publish.yml

 

- stage: Deploy_SDW
  dependsOn: 
  - Publish_DCR_Rules

  displayName: Deploy to SDW
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-SDW - Environment Key Vault Secrets
  jobs:
  - template: pipeline/deploy.yml
    parameters:
      pool: DCT Build Pool
      environmentName: SDW
      azureSubscription: DCOL-Shadow
      dataCollectionRules_DCOL_SDW_ServiceFabric_DCR_name: DCOL-SDW-ServiceFabric-DCR
      workspaces_DCOL_SDW_OPS_WEU_Workspace_externalid: /subscriptions/4ff47917-ac4e-432a-b314-a6525434afcb/resourceGroups/dcol-sdw-ops-weu/providers/Microsoft.OperationalInsights/workspaces/DCOL-SDW-OPS-WEU-Workspace
      

 
#- stage: Deploy_MO
#  dependsOn: 
#  - Publish_SFClusterAlerts
#  - Deploy_SDW
#  displayName: Deploy to MO
#  variables:
#  - name: tagEnvironment
#    value: Dev/Test
#  - group: DCOL-MO - Environment Key Vault Secrets
#  - group: Common - tags MO
#  jobs:
#  - template: pipeline/deploy.yml
#    parameters:
#      pool: DCT Build Pool
#      environmentName: MO
#      azureSubscription: DCOL-MO-VSTS
#      metricAlerts_VM_CPU_Alert_name: VM-CPU-Alert-MO
#      virtualMachineScaleSets_monitor_externalid: /subscriptions/2f538936-0715-4dfd-83da-6b8c5a399d6a/resourceGroups/dcol-mo-servicefabricdas-weu/providers/Microsoft.Compute/virtualMachineScaleSets/monitor
#      actionGroups_dcol_dasalerts_actiongroup_externalid: /subscriptions/2f538936-0715-4dfd-83da-6b8c5a399d6a/resourceGroups/DCOL-MO-OPS-WEU/providers/microsoft.insights/actionGroups/SFA-FCS-MO-PV2
#      metricAlerts_VM_Available_Memory_Alert_name: VM-Available-Memory-Alert-MO
#      actiongroups_dcol_dasalerts_actiongroup_weu_externalid: /subscriptions/2f538936-0715-4dfd-83da-6b8c5a399d6a/resourceGroups/DCOL-MO-OPS-WEU/providers/microsoft.insights/actionGroups/SFA-FCS-MO-PV2
#      metricAlerts_VM_Availability_Alert_name: VM-Availability-Alert-MO
#      actionGroups_SFCluster_VMAlerts_externalid: /subscriptions/2f538936-0715-4dfd-83da-6b8c5a399d6a/resourceGroups/DCOL-MO-OPS-WEU/providers/microsoft.insights/actionGroups/SFA-FCS-MO-PV2

#- stage: Deploy_PP
#  dependsOn: 
#  - Publish_MonitoringMetrics
#  - Deploy_MO
#  displayName: Deploy to PP
#  variables:
#  - name: tagEnvironment
#    value: Pre-Production
#  - group: DCOL-PP - Environment Key Vault Secrets
#  jobs:
#  - template: pipeline/deploy.yml
#    parameters:
#      pool: DCT Build Pool
#      environmentName: PP
#      azureSubscription: DCOLPPVSTS
#      storageAccountName: dcolppstoragemonitorweu
#      workspaceResourceId: /subscriptions/931bc9f6-359c-4f65-a753-1ee191a1fd6c/resourcegroups/dcol-pp-ops-weu/providers/microsoft.operationalinsights/workspaces/dcol-pp-oms-weu
#      dasActionGroupWebhookUri1: $(dasActionGroupWebhookUri)
#      mgDasActionGroupWebhookUri1: $(mgDasActionGroupWebhookUri)
#      smartDetectionActionGroupId: /subscriptions/931BC9F6-359C-4F65-A753-1EE191A1FD6C/resourceGroups/DCOL-PP-AppSrvEnv-WEU/providers/microsoft.insights/actionGroups/application%20insights%20smart%20detection
#      serviceBusActionGroupId: /subscriptions/931BC9F6-359C-4F65-A753-1EE191A1FD6C/resourceGroups/DCOL-PP-ServiceFabricDAS-WEU/providers/microsoft.insights/actionGroups/DCOL-PP-dasalerts-actiongroup-WEU
#      dasAlertSlackChannelUri: $(SlackChannelUri)
#      mngAlertSlackChannelUri: $(SlackChannelUri2)
#      appInsightsApiKey: $(AppInsightsAuthValue)

#- stage: Deploy_PD
#  dependsOn: 
#  - Publish_SFClusterAlerts
#  - Deploy_MO
#  displayName: Deploy to PD
#  variables:
#  - name: tagEnvironment
#    value: Production
#  - group: DCOL-PD - Environment Key Vault Secrets
#  jobs:
#  - template: pipeline/deploy.yml
#    parameters:
#      pool: DCT Build Pool
#      environmentName: PD
#      azureSubscription: DCOLPDVSTS
#      metricAlerts_VM_CPU_Alert_name: VM-CPU-Alert-PD
#      virtualMachineScaleSets_monitor_externalid: /subscriptions/6c93f7dc-6c36-4ea6-8de3-3f4574f88027/resourceGroups/DCOL-PD-ServiceFabricDas-WEU/providers/Microsoft.Compute/virtualMachineScaleSets/monitor
#      actionGroups_dcol_dasalerts_actiongroup_externalid: /subscriptions/6C93F7DC-6C36-4EA6-8DE3-3F4574F88027/resourceGroups/DCOL-PD-ServiceFabricDAS-WEU/providers/microsoft.insights/actionGroups/DCOL-PD-dasalerts-actiongroup-WEU
#      metricAlerts_VM_Available_Memory_Alert_name: VM-Available-Memory-Alert-PD
#      actiongroups_dcol_dasalerts_actiongroup_weu_externalid: /subscriptions/6C93F7DC-6C36-4EA6-8DE3-3F4574F88027/resourceGroups/DCOL-PD-ServiceFabricDAS-WEU/providers/microsoft.insights/actionGroups/DCOL-PD-dasalerts-actiongroup-WEU
#      metricAlerts_VM_Availability_Alert_name: VM-Availability-Alert-PD
#      actionGroups_SFCluster_VMAlerts_externalid: /subscriptions/6C93F7DC-6C36-4EA6-8DE3-3F4574F88027/resourceGroups/DCOL-PD-ServiceFabricDAS-WEU/providers/microsoft.insights/actionGroups/DCOL-PD-dasalerts-actiongroup-WEU
