parameters:
  pool:
  azureSubscription:
  location: 'westeurope'
  environmentName:
  metricAlerts_VM_CPU_Alert_name:
  virtualMachineScaleSets_monitor_externalid:
  actionGroups_dcol_dasalerts_actiongroup_externalid:
  metricAlerts_VM_Available_Memory_Alert_name:
  actiongroups_dcol_dasalerts_actiongroup_weu_externalid:
  metricAlerts_VM_Availability_Alert_name:
  actionGroups_SFCluster_VMAlerts_externalid:
  
  

jobs:
- deployment: DeploySFClusterAlerts
  pool:
    name: ${{ parameters.pool }}
    demands:
    - ReleaseEnvironment -equals ${{ parameters.environmentName }}
  environment: ${{ parameters.environmentName }}
  variables: 
    - name: resourceGroupName
      value: '$(Service)-${{ parameters.environmentName }}-ServiceFabricDAS-$(RegionPrimaryCode)'
    - name: metricAlerts_VM_CPU_Alert_name
      value: '${{ parameters.metricAlerts_VM_CPU_Alert_name }}'
    - name: virtualMachineScaleSets_monitor_externalid
      value: ${{ parameters.virtualMachineScaleSets_monitor_externalid }}
    - name: actionGroups_dcol_dasalerts_actiongroup_externalid
      value: ${{ parameters.actionGroups_dcol_dasalerts_actiongroup_externalid }}
    - name: metricAlerts_VM_Available_Memory_Alert_name
      value: ${{ parameters.metricAlerts_VM_Available_Memory_Alert_name }}
    - name: actiongroups_dcol_dasalerts_actiongroup_weu_externalid
      value: ${{ parameters.actiongroups_dcol_dasalerts_actiongroup_weu_externalid }}
    - name: metricAlerts_VM_Availability_Alert_name
      value: ${{ parameters.metricAlerts_VM_Availability_Alert_name }}
    - name: actionGroups_SFCluster_VMAlerts_externalid
      value: ${{ parameters.actionGroups_SFCluster_VMAlerts_externalid }}
    
    
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzurePowerShell@5
          displayName: Create solution resource group
          inputs:
            azureSubscription: '${{ parameters.azureSubscription }}'
            ScriptType: 'InlineScript'
            Inline: 'New-AzResourceGroup -Name ${{ variables.resourceGroupName }} -Location "${{ parameters.location }}" -Tag $(tags) -Force'
            azurePowerShellVersion: 'LatestVersion'

        - task: AzurePowerShell@5
          displayName: Set subscription id variable
          inputs:
            azureSubscription: '${{ parameters.azureSubscription }}'
            ScriptType: 'InlineScript'
            Inline: |
              $subscriptionId = (Get-AzSubscription).SubscriptionId
              Write-Host "variable=subscriptionId: $subscriptionId"
              Write-Host "##vso[task.setvariable variable=subscriptionId;]$subscriptionId"
            azurePowerShellVersion: 'LatestVersion'

        - task: AzureResourceGroupDeployment@2
          displayName: Deploy Solution Resources
          inputs:
            azureSubscription: '${{ parameters.azureSubscription }}'
            resourceGroupName: '${{ variables.resourceGroupName }}'
            location: '${{ parameters.location }}'
            csmFile: '$(Pipeline.Workspace)/drop/Infrastructure/SFA.DAS.Payments.SFCluster.Alerts/azure/template.json'
            csmParametersFile: '$(Pipeline.Workspace)/drop/Infrastructure/SFA.DAS.Payments.SFCluster.Alerts/azure/parameters.json'
            overrideParameters: '-metricAlerts_VM_CPU_Alert_name "${{ variables.metricAlerts_VM_CPU_Alert_name }}" -virtualMachineScaleSets_monitor_externalid "${{ variables.virtualMachineScaleSets_monitor_externalid }}" -actionGroups_dcol_dasalerts_actiongroup_externalid "${{ variables.actionGroups_dcol_dasalerts_actiongroup_externalid }}" -metricAlerts_VM_Available_Memory_Alert_name "${{ variables.metricAlerts_VM_Available_Memory_Alert_name }}" -actiongroups_dcol_dasalerts_actiongroup_weu_externalid "${{ variables.actiongroups_dcol_dasalerts_actiongroup_weu_externalid }}" -metricAlerts_VM_Availability_Alert_name "${{ parameters.metricAlerts_VM_Availability_Alert_name }}" -actionGroups_SFCluster_VMAlerts_externalid "${{ variables.actionGroups_SFCluster_VMAlerts_externalid }}"'
            deploymentOutputs: armoutputs