variables:
- group: Common - Project Level
- group: Common - Connection String
- group: Common - Database Names
- group: Common - Database Usernames

resources:
  repositories:
  - repository: self

stages:
- stage: Publish_MonitoringMetrics
  displayName: Publish MonitoringMetrics

  jobs:
  - template: pipeline/publish.yml

- stage: Deploy_DAS
  dependsOn: Publish_MonitoringMetrics
  displayName: Deploy to DAS
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-DAS - Environment Key Vault Secrets
  jobs:
  - template: pipeline/deploy.yml
    parameters:
      pool: DCT Build Pool
      environmentName: DAS
      azureSubscription: DCT-VSO
      storageAccountName: dcoldasstoragemonitorweu
      workspaceResourceId: /subscriptions/12f72527-6622-45d3-90a4-0a5d3644c45c/resourcegroups/dcol-dev-oms-weu/providers/microsoft.operationalinsights/workspaces/dcol-dev-oms-weu
      dasActionGroupWebhookUri: https://dcol-ete-monitoringalerts-weu.azurewebsites.net/api/HttpTrigger1?code=psdMwRn/a4D7l5Rx/l5orF0dptv8AR8uUZediTPAU4dHhmLaSd/nuA==&name=Bob
      mgDasActionGroupWebhookUri: https://dcol-ete-monitoringalerts-weu.azurewebsites.net/api/HttpTrigger1?code=psdMwRn/a4D7l5Rx/l5orF0dptv8AR8uUZediTPAU4dHhmLaSd/nuA==&name=Bob
      smartDetectionActionGroupId: /subscriptions/12F72527-6622-45D3-90A4-0A5D3644C45C/resourceGroups/DCOL-DAS-AppSrvEnv-WEU/providers/microsoft.insights/actionGroups/application%20insights%20smart%20detection
      serviceBusActionGroupId: /subscriptions/12F72527-6622-45D3-90A4-0A5D3644C45C/resourceGroups/DCOL-DAS-AppSrvEnv-WEU/providers/microsoft.insights/actionGroups/application%20insights%20smart%20detection


- stage: Deploy_DST
  dependsOn: Publish_MonitoringMetrics
  displayName: Deploy to DST
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-DST - Environment Key Vault Secrets
  jobs:
  - template: pipeline/deploy.yml
    parameters:
      pool: DCT Build Pool
      environmentName: DST
      azureSubscription: DCT-VSO
      storageAccountName: dcoldststoragemonitorweu
      workspaceResourceId: /subscriptions/12f72527-6622-45d3-90a4-0a5d3644c45c/resourcegroups/dcol-dev-oms-weu/providers/microsoft.operationalinsights/workspaces/dcol-dev-oms-weu
      dasActionGroupWebhookUri: https://dcol-ete-monitoringalerts-weu.azurewebsites.net/api/HttpTrigger1?code=psdMwRn/a4D7l5Rx/l5orF0dptv8AR8uUZediTPAU4dHhmLaSd/nuA==
      mgDasActionGroupWebhookUri: https://dcol-ete-monitoringalerts-weu.azurewebsites.net/api/HttpTrigger1?code=psdMwRn/a4D7l5Rx/l5orF0dptv8AR8uUZediTPAU4dHhmLaSd/nuA==
      smartDetectionActionGroupId: /subscriptions/12F72527-6622-45D3-90A4-0A5D3644C45C/resourceGroups/DCOL-DST-AppSrvEnv-WEU/providers/microsoft.insights/actionGroups/application%20insights%20smart%20detection
      serviceBusActionGroupId: /subscriptions/12F72527-6622-45D3-90A4-0A5D3644C45C/resourceGroups/DCOL-DST-AppSrvEnv-WEU/providers/microsoft.insights/actionGroups/application%20insights%20smart%20detection
       
#      

#- stage: Deploy_SIT
#  dependsOn: 
#  - Publish_ADF
#  - Deploy_DST
#  displayName: Deploy to SIT
#  variables:
#  - name: tagEnvironment
#    value: Dev/Test
#  - group: DCOL-SIT - Environment Key Vault Secrets
#  jobs:
#  - template: pipeline/deploy.yml
#    parameters:
#      pool: DCT Build Pool
#      environmentName: SIT
#      azureSubscription: DCT-VSO
#      deployFactory: true

#- stage: Deploy_SDW
#  dependsOn: 
#  - Publish_ADF
#  - Deploy_SIT
#  displayName: Deploy to SDW
#  variables:
#  - name: tagEnvironment
#    value: Dev/Test
#  - group: DCOL-SDW - Environment Key Vault Secrets
#  jobs:
#  - template: pipeline/deploy.yml
#    parameters:
#      pool: DCT Build Pool
#      environmentName: SDW
#      azureSubscription: DCOL-Shadow
#      deployFactory: true
#- stage: Deploy_MO
#  dependsOn: 
#  - Publish_ADF
#  - Deploy_SDW
#  displayName: Deploy to MO
#  variables:
#  - name: tagEnvironment
#    value: Dev/Test
#  - group: DCOL-MO - Environment Key Vault Secrets
#  jobs:
#  - template: pipeline/deploy.yml
#    parameters:
#      pool: DCT Build Pool
#      environmentName: MO
#      azureSubscription: DCOL-MO-VSTS
#      deployFactory: true

#- stage: Deploy_PD
#  dependsOn: 
#  - Publish_ADF
#  - Deploy_MO
#  displayName: Deploy to PD
#  variables:
#  - name: tagEnvironment
#    value: Production
#  - group: DCOL-PD - Environment Key Vault Secrets
#  jobs:
#  - template: pipeline/deploy.yml
#    parameters:
#      pool: DCT Build Pool
#      environmentName: PD
#      azureSubscription: DCOLPDVSTS
#      deployFactory: true