Create TABLE [Payments2].[Job]
( 
	JobId BIGINT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Job PRIMARY KEY CLUSTERED,
	JobType TINYINT NOT NULL,
	StartTime DATETIMEOFFSET NOT NULL,	
	EndTime DATETIMEOFFSET NULL, 
	[Status] TINYINT NOT NULL,
	CreationDate DATETIMEOFFSET NOT NULL,
	DCJobId BIGINT NULL,
	Ukprn BIGINT NULL, 
	IlrSubmissionTime DATETIME NULL,
	LearnerCount INT NULL,
	AcademicYear SMALLINT NOT NULL,
	CollectionPeriod TINYINT NOT NULL,
	DataLocksCompletionTime DATETIMEOFFSET NULL,
	DCJobSucceeded BIT NULL,
	DCJobEndTime DATETIMEOFFSET NULL
)
GO