// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.FundingSource.AcceptanceTests.Tests.ACT2_TransTypes_1To3_Basic_Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("R13 - First payment, no previous payments. Also completion.")]
    public partial class R13_FirstPaymentNoPreviousPayments_AlsoCompletion_Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OnTime_Completion_But_Late_OnProg_NoHistory.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "R13 - First payment, no previous payments. Also completion.", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("the current processing period is 13", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.And("a learner with LearnRefNumber learnref1 and Uln 10000 undertaking training with t" +
                    "raining provider 10000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "PriceEpisodeIdentifier",
                        "Period",
                        "ULN",
                        "TransactionType",
                        "Amount",
                        "SfaContributionPercentage"});
            table1.AddRow(new string[] {
                        "p1",
                        "1",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "2",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "3",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "4",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "5",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "6",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "7",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "8",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "9",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "10",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "11",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "12",
                        "10000",
                        "Learning_1",
                        "600",
                        "0.90000"});
            table1.AddRow(new string[] {
                        "p1",
                        "13",
                        "10000",
                        "Completion_2",
                        "1800",
                        "0.90000"});
#line 8
 testRunner.And("the payments due component generates the following contract type 2 payable earnin" +
                    "gs:", ((string)(null)), table1, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Contract Type 2 Learning payment")]
        [NUnit.Framework.CategoryAttribute("Non-DAS")]
        [NUnit.Framework.CategoryAttribute("MissingSubmission")]
        [NUnit.Framework.CategoryAttribute("Learning_1")]
        [NUnit.Framework.CategoryAttribute("Completion_2")]
        [NUnit.Framework.CategoryAttribute("CoInvested")]
        public virtual void ContractType2LearningPayment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Contract Type 2 Learning payment", null, new string[] {
                        "Non-DAS",
                        "MissingSubmission",
                        "Learning_1",
                        "Completion_2",
                        "CoInvested"});
#line 32
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 34
 testRunner.When("a payable earning event is received", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "LearnRefNumber",
                        "Ukprn",
                        "PriceEpisodeIdentifier",
                        "Period",
                        "ULN",
                        "TransactionType",
                        "FundingSource",
                        "Amount"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "1",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "1",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "2",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "2",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "3",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "3",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "4",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "4",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "5",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "5",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "6",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "6",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "7",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "7",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "8",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "8",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "9",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "9",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "10",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "10",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "11",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "11",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "12",
                        "10000",
                        "Learning_1",
                        "CoInvestedSfa_2",
                        "540"});
            table2.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "12",
                        "10000",
                        "Learning_1",
                        "CoInvestedEmployer_3",
                        "60"});
#line 36
 testRunner.Then("the funding source component will generate the following contract type 2 coinvest" +
                    "ed payments:", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Contract Type 2 completion payment")]
        public virtual void ContractType2CompletionPayment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Contract Type 2 completion payment", null, ((string[])(null)));
#line 64
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 66
 testRunner.When("a payable earning event is received", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "LearnRefNumber",
                        "Ukprn",
                        "PriceEpisodeIdentifier",
                        "Period",
                        "ULN",
                        "TransactionType",
                        "FundingSource",
                        "Amount"});
            table3.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "13",
                        "10000",
                        "Completion_2",
                        "CoInvestedSfa_2",
                        "1620"});
            table3.AddRow(new string[] {
                        "learnref1",
                        "10000",
                        "p1",
                        "13",
                        "10000",
                        "Completion_2",
                        "CoInvestedEmployer_3",
                        "180"});
#line 68
 testRunner.Then("the funding source component will generate the following contract type 2 coinvest" +
                    "ed payments:", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
